sonar.projectKey=danewrx_dane.gg_37e11e49-3ba4-4d28-9097-c4e47871cd0d
sonar.projectName=dane.gg

sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src,e2e
sonar.test.inclusions=**/*.test.ts,**/*.test.js,**/*.spec.ts,**/*.spec.js

sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/.svelte-kit/**,**/drizzle/**,**/static/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info