CREATE TABLE IF NOT EXISTS "website"."themes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(100) NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT false,
	"is_default" boolean DEFAULT false,
	"primary_color" varchar(50) DEFAULT '#ffffff',
	"secondary_color" varchar(50) DEFAULT '#a1a1aa',
	"accent_color" varchar(50) DEFAULT '#6366f1',
	"background_color" varchar(50) DEFAULT '#0a0a0a',
	"surface_color" varchar(50) DEFAULT '#1a1a1a',
	"border_color" varchar(50) DEFAULT '#2a2a2a',
	"text_primary" varchar(50) DEFAULT '#ffffff',
	"text_secondary" varchar(50) DEFAULT '#a1a1aa',
	"text_muted" varchar(50) DEFAULT '#71717a',
	"background_image" varchar(500),
	"background_image_external" boolean DEFAULT false,
	"background_overlay" varchar(50) DEFAULT 'rgba(0, 0, 0, 0.7)',
	"background_blur" integer DEFAULT 0,
	"background_position" varchar(50) DEFAULT 'center center',
	"background_size" varchar(50) DEFAULT 'cover',
	"background_attachment" varchar(20) DEFAULT 'fixed',
	"font_family" varchar(255) DEFAULT 'Inter',
	"heading_font_family" varchar(255) DEFAULT 'Inter',
	"font_scale" varchar(10) DEFAULT '1',
	"border_radius" varchar(20) DEFAULT '8px',
	"custom_css" text,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
