/** Default Google font names inserted when the `fonts` table is empty (API + seed + boot). */
export const DEFAULT_GOOGLE_FONT_NAMES = [
	'Inter',
	'Roboto',
	'Open Sans',
	'Lato',
	'Montserrat',
	'Poppins',
	'Source Sans Pro',
	'Nunito',
	'Raleway',
	'Ubuntu',
	'Playfair Display',
	'Merriweather',
	'PT Sans',
	'Oswald',
	'Quicksand',
	'Work Sans',
	'Fira Sans',
	'Rubik',
	'Karla',
	'Manrope',
	'Space Grotesk',
	'DM Sans',
	'JetBrains Mono',
	'Fira Code',
	'Rajdhani',
	'Orbitron'
] as const;
